# Generated by Django 4.1.7 on 2023-03-09 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=255)),
                ('api_version', models.CharField(max_length=255)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('instance_url', models.CharField(blank=True, max_length=255)),
                ('component_option', models.CharField(choices=[('wildcard_only', 'Wildcard Only'), ('all', 'All Components'), ('unmanaged', 'Exclude Managed'), ('none', 'No Packaged Components')], max_length=255)),
                ('package', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('in_folder', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildpackage.package')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildpackage.componenttype')),
            ],
        ),
    ]
